### PR TITLE
Added flip cards

### LINKED ISSUE #2: Framework to be used
The project will be restricted to HTML, CSS, or some frameworks can be used here?

### PR DESCRIPTION
**Pull request by Tishasoumya-02**
Added flip cards.
Closes #2

### CODE REVIEW

**Comment by AADI-1331** [comment]
Can u give a short clip of your output.

**Comment by Tishasoumya-02** [comment]
https://user-images.githubusercontent.com/66815801/135753849-530d5e1b-7850-4090-97b2-25138b778951.mp4

**Comment by AADI-1331** [comment]
that's awesome

**Comment by AADI-1331** [comment]
I have a question , if I add a fifth card how it will look on the template can u share that

**Comment by AADI-1331** [comment]
I saw something wrong with that four buttons on the top.
aaa
the header should look like this, in urs images are on top of the buttons.

**Comment by AADI-1331** [comment]
> I saw something wrong with that four buttons on the top. aaa the header should look like this, in urs images are on top of the buttons.

2) text behind the cards is also disturbed.

**Comment by Tishasoumya-02** [comment]
style

**Comment by Tishasoumya-02** [comment]
> I saw something wrong with that four buttons on the top. aaa the header should look like this, in urs images are on top of the buttons.

Yes I saw that too..working on it

**Comment by AADI-1331** [comment]
can u add three rows of cards and sent a clip of that

**Comment by Tishasoumya-02** [comment]
> can u add three rows of cards and sent a clip of that

It works the same for all the rows ...cards are first added in the center of the page and then other two are added just beside it

**Comment by AADI-1331** [comment]
> > can u add three rows of cards and sent a clip of that
> 
> It works the same for all the rows ...cards are first added in the center of the page and then other two are added just beside it

oki

**Comment by Tishasoumya-02** [comment]
The text behind the card -> "Scarlett" centered

fontstyle

**Comment by Tishasoumya-02** [comment]
The icons are now in the right place 

button

**Comment by AADI-1331** [comment]
checkout the new look

**Comment by Tishasoumya-02** [comment]
> checkout the new look

Looks great 💥

**Pull request merged**
