### PR TITLE
added animation on scroll

### PR DESCRIPTION
**Pull request by ksalokya**
added animation on scroll, have a look and give label of hacktoberfest.

### CODE REVIEW

**Comment by AADI-1331** [comment]
error

**Comment by AADI-1331** [comment]
Screenshot (2)

**Comment by AADI-1331** [comment]
error

**Comment by ksalokya** [comment]
Screenshot 2021-10-01 134612


In my branch it's fine, if you will say I can again generate a PR on latest one.

**Comment by AADI-1331** [comment]
no no its fine bro

**Comment by AADI-1331** [comment]
i fixed it out

**Comment by ksalokya** [comment]
that's nice, thank you.

**Pull request merged**
