### PR TITLE
Added a footer

### LINKED ISSUE #37: Footer for the website
I'd like to make a footer for this website. I'll add various links and a subscribe option

### PR DESCRIPTION
**Pull request by SushantPatial**
Resolves: #37

Please let me know if it needs changes

image

On hover: 
image

image

### CODE REVIEW

**Comment by AADI-1331** [comment]
op

**Comment by AADI-1331** [comment]
where are the hover effect images on the buttons

**Comment by AADI-1331** [comment]
Screenshot (22)

**Comment by AADI-1331** [comment]
https://user-images.githubusercontent.com/78849620/136056937-1ff424fb-fac6-4055-bb43-d95c3c014a14.mp4

**Comment by AADI-1331** [comment]
can u adjust the width of the footer

**Comment by SushantPatial** [comment]
> can u adjust the width of the footer

Sure, how do you want it? The same as shown in the above video?

**Comment by AADI-1331** [comment]
> > can u adjust the width of the footer
> 
> Sure, how do you want it? The same as shown in the above video?

ya the video i shared with you ,can u make it wider like header.

**Pull request merged**
