### PR TITLE
added the wireframe with a new look

### PR DESCRIPTION
**Pull request by Pranavanbu28**
I've added the wireframe with a new look and feel. Please do take a look. Fixed issue #23

### CODE REVIEW

**Comment by Pranavanbu28** [comment]
@AADI-1331 Please do take a look and tell me if anything has to be changed. And before merging I request you to add "hacktoberfest-accepted" label.

**Comment by AADI-1331** [comment]
adding labels or not it doesn't matters, its only matters if I add the topic to repo

**Comment by Pranavanbu28** [comment]
is my design alright brother? or should I make some changes?

**Comment by AADI-1331** [comment]
where's the code.

**Comment by Pranavanbu28** [comment]
Its a prototype designed using figma

**Comment by Pranavanbu28** [comment]
this is a wireframe

**Comment by AADI-1331** [comment]
so have you worked on it

**Comment by Pranavanbu28** [comment]
on the code?

**Comment by AADI-1331** [comment]
it means it just a image

**Comment by Pranavanbu28** [comment]
I did it using figma

**Comment by AADI-1331** [comment]
I mean if I merge it, it will change the CSS?

**Comment by Pranavanbu28** [comment]
no

**Comment by Pranavanbu28** [comment]
I basically redesigned the website just the design

**Comment by Pranavanbu28** [comment]
people can refer this for making a real one

**Comment by AADI-1331** [comment]
then bro? actually, i am confused and curious to know about it

**Comment by Pranavanbu28** [comment]
tell brother

**Comment by AADI-1331** [comment]
in short i really liked it

**Comment by Pranavanbu28** [comment]
Thanks!

**Comment by AADI-1331** [comment]
so after merging if i run my index.html it will look like this

**Comment by Pranavanbu28** [comment]
No no. Its just a design which I did. People can refer this design to build the website

**Comment by Pranavanbu28** [comment]
You can add this to the readme so that others can see

**Comment by AADI-1331** [comment]
oh damn so can u make this using css

**Comment by Pranavanbu28** [comment]
yess

**Comment by Pranavanbu28** [comment]
But it'll take a lot of time

**Comment by AADI-1331** [comment]
then plz do some then other contributors can learn with ur code

**Comment by Pranavanbu28** [comment]
I'll try my best

**Comment by AADI-1331** [comment]
for now this a image that u added in readme

**Comment by Pranavanbu28** [comment]
yes

**Comment by AADI-1331** [comment]
ok

**Pull request merged**
