### PR TITLE
Made it a bit more responsive

### PR DESCRIPTION
**Pull request by Anushh23**
# Made it a bit more responsive
## Before:
Before
## After:
After

### CODE REVIEW

**Comment by AADI-1331** [comment]
sorry, but it was perfect and looks like after output and I think u edit it again.

**Comment by AADI-1331** [comment]
see the read me

**Comment by Anushh23** [comment]
@AADI-1331 It is not mobile responsive.
When the width is less than 400px it tends to overflow!!
This is how it'll look in a moto g phone, I've added the dimensions too.
# before:
-----------
Screenshot (62)
# after:
--------------
Screenshot (63)

**Comment by Anushh23** [comment]
Hey, can you please add the hacktoberfest-accepted tag. Thanks

**Comment by AADI-1331** [comment]
in this, we don't have to add labels for every issue, the topic should be hackctober fest accepted

**Comment by Anushh23** [comment]
Oh okay , wasn't aware of that. 
Anyway, great work!
Thanks :)

**Pull request merged**
